pipeline:
  build:
    image: golang:1.7
    pull: true
    environment:
      - GOPATH=/drone
      - GOBIN=/drone/bin
    commands:
      - go get
      - go build
  notify:
      irc:
        prefix: build
        nick: pufferbuild
        channel: #pufferpanel
        server:
            host: irc.esper.net
            tls: true
            port: 6697