pipeline:
  build:
    image: golang
    pull: true
    commands:
      - go get
  notify:
      irc:
        prefix: build
        nick: pufferbuild
        channel: #pufferpanel
        server:
            host: irc.esper.net
            tls: true
            port: 6697