pipeline:
  build:
    image: golang
    environment:
      - GOPATH=/drone
      - GOBIN=/drone/bin
    commands:
      - go get
      - go build

  notify:
    irc:
    prefix: build
    nick: PufferCI
    channel: $$IRCCHANNEL
    server:
        host: irc.esper.net
        tls: true
        port: 6697
    when:
        status: [ success, failure ]